version: '3.3'
services:
  jenkins:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - app-network

volumes:
    jenkins-log:
    jenkins-data:

networks:
  app-network:
    driver: bridge
      

