version: "3.3"

services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.9.2-community
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - sonarnet
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

jenkins:
    # restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-local
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-log:/var/log/jenkins
      - jenkins-data:/var/jenkins_home
    networks:
      - app-network
  db:
    container_name: sonardb
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  sonarscanner:
    container_name: sonarscanner
    image: newtmitch/sonar-scanner
    networks:
      - sonarnet
    volumes:
      - sonarvol:/usr/src

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  sonarvol:

  dbmysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root@pass
      MYSQL_DATABASE: jenkins_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: jenkins


  tomcat:
    restart: always
    image: tomcat:9
    volumes:
      - tomcat_data:/var/lib/tomcat
    container_name: tomcat-local
    ports:
      - "8085:8080"

  sonaqube:
    image: sonarqube
    networks:
      - sonarnet
    volumes:
      - sonaqube_data:/etc/sonaqube
    ports:
      - "9000:9000"
    container_name: sonarqube-local

  sonarscanner:
    container_name: sonarscanner
    image: newtmitch/sonar-scanner
    networks:
      - sonarnet
    volumes:
      - sonarvol:/usr/src

  db:
    image: postgres:12
    restart: always
    container_name: postgres-local
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

